version: 2

sources:
  - name: MYDB
    schema: PUBLIC_RAW
    tables:
      - name: TIMESERIES
        identifier: timeseries
      - name: SOURCE_ORG
        identifier: source_org
      - name: DIM_ORG_TYPE
        identifier: dim_org_type
      - name: DWH_DIM_ORG
        identifier: dwh_dim_org
      - name: DIM_USER_ROW
        identifier: dim_user_row
      - name: LCM_USER
        identifier: lcm_user
      - name: ADDRESS_REF
        identifier: address_ref
      - name: SOURCE_TABLE
        identifier: source_table
      

  
